### PR TITLE
Add emergency datasets & APIs

### PR DESCRIPTION
**Pull request by CodeMacabre**
Moves 'Natural Disaster' section into new Emergency section. Add new emergency datasets and APIs to Emergency section.

### CODE REVIEW

**Comment by CodeMacabre** [comment]
Is there anything needed to get this merged? I'm happy to make changes if they're required. 😃

**Comment by jdorfman** [comment]
@CodeMacabre hey sorry for the delay. Yeah I think you can just put these under other instead of a whole new category.

**Comment by CodeMacabre** [comment]
@jdorfman Thanks! I've moved the Emergency API into Other and reverted my change to the Natural Disasters category (and updated it).

Also, I noticed Natural Disasters was missing its entry in the TOC, so I've added that too.

**Comment by CodeMacabre** [comment]
@jdorfman Not entirely sure why checks have failed, but I've updated this PR with the changes you requested. Could you take a look please and let me know if anything else needs updating?

**Pull request closed without merging**
