### PR TITLE
UK Environmental Agency

### PR DESCRIPTION
**Pull request by stephan2307**
Added 6 JSON endpoints for the UK Environmental agency

### CODE REVIEW

**Comment by DraftYeti5608** [comment]
You have some trailing spaces in your commit which is preventing the check from passing, make sure no lines end in a space and the check should pass.

**Comment by stephan2307** [comment]
Updated

**Comment by DraftYeti5608** [comment]
If you move the datasets to be under `weather` instead of `government`, I'll merge.

**Comment by stephan2307** [comment]
did the change but not sure what the conflict is now.

**Comment by DraftYeti5608** [comment]
I'll look into it.

**Comment by hdavies5608** [comment]
You still have a merge conflict, you can use the command line to fix it or open a new Pull Request that has the latest changes from master.

**Comment by jdorfman** [comment]
@stephan2307 please make an individual pull request for each suggestion. Closing this, please resubmit. =)

This rule wasn't present when you made the pull request, but I have to enforce it to minimize conflicts. Thanks

**Pull request closed without merging**
