### PR TITLE
Addition of historical India GDP since 1960

### PR DESCRIPTION
**Pull request by wandeg**
#21

### CODE REVIEW

**Comment by hdavies5608** [comment]
You have some merge conflicts on all your open pull requests, if you could fix them all I'll merge them.

**Comment by wandeg** [comment]
Conflict fixed

**Comment by hdavies5608** [comment]
Could you fix this conflict and add GDP to the contents? 

Because this pull request includes that of your others I'll close those and merge this one.

**Comment by hdavies5608** [comment]
Can you add a GDP section to the contents list please :)

**Comment by wandeg** [comment]
Done

**Comment by hdavies5608** [comment]
Awesome! Thanks for that

**Pull request merged**
