### PR TITLE
Added Museum Victoria Collections API

### PR DESCRIPTION
**Pull request by spar**
more information at: https://collections.museumvictoria.com.au/developers

### CODE REVIEW

**Comment by spar** [comment]
@jdorfman is this something you can take a look at?

**Comment by jdorfman** [comment]
@spar check out my feedback above

```
Just link directly to a/the JSON endpoint and remove the Developer Information and we will be good to go.
```

**Comment by spar** [comment]
@jdorfman removed developer information, thanks

**Comment by jdorfman** [comment]
thanks @spar great addition =)

**Pull request merged**
