### PR TITLE
Added some car brands

### PR DESCRIPTION
**Pull request by pliguori**

### CODE REVIEW

**Comment by pliguori** [comment]
#21

**Comment by hdavies5608** [comment]
If you can fix the conflict I can merge.

**Comment by jdorfman** [comment]
I am having no luck fixing this.

```
> git checkout -b pliguori-#21-new-jsons master
Switched to a new branch 'pliguori-#21-new-jsons'
 ~/github/jdorfman/Awesome-JSON-Datasets  ± (pliguori-#21-new-jsons ✓)

> git pull https://github.com/pliguori/awesome-json-datasets.git #21-new-jsons
From https://github.com/pliguori/awesome-json-datasets
 * branch            HEAD       -> FETCH_HEAD
Already up-to-date.
```

=/

**Comment by jdorfman** [comment]
Hey @pliguori please make an individual pull request for each suggestion. Closing this, please resubmit. =)

This rule wasn't present when you made the pull request, but I have to enforce it to minimize conflicts. Thanks

**Pull request closed without merging**
