### PR TITLE
Added movie section with examples

### PR DESCRIPTION
**Pull request by jschiarizzi**
Use www.omdbapi.com to generate info on movies based on titles.

### CODE REVIEW

**Comment by jschiarizzi** [comment]
Hmmm I don't know what that check means...

**Comment by DraftYeti5608** [comment]
I believe the check fails because of the URL on line 514 of the file, try removing it or encasing it in a markdown link.

**Comment by jschiarizzi** [comment]
Woo, did that and it passed. Thanks DraftYeti, cheers.

**Comment by DraftYeti5608** [comment]
No problem.

**Comment by jdorfman** [comment]
Now that is what I call teamwork! Great job @jschiarizzi and @DraftYeti5608 👍

**Comment by jdorfman** [comment]
@DraftYeti5608 interested in becoming a maintainer? Could really use your help =) email me jdorfman-at-stickermule.com

**Pull request merged**
