### PR TITLE
Fixed wizards website link. Added https do mtgjson links.

### PR DESCRIPTION
**Pull request by lsmoura**

### CODE REVIEW

**Comment by lsmoura** [comment]
I came to this repository from a hacktoberfest mail... But I can't add Hacktoberfest as a label. Could the maintainer please add it for me? Thanks!

**Comment by jdorfman** [comment]
@lsmoura fix the conflict and I will merge it. Thanks

**Comment by lsmoura** [comment]
@jdorfman - Conflict fixed!

**Comment by hdavies5608** [comment]
@lsmoura Thanks for that, merged!

**Pull request merged**
